@extends('driver.layouts.master')
@push('css')
   <style>
       .modal-2fa-footer {
           padding: 15px;
           border-top: 1px solid #e5e5e5;
           text-align: center;
           background-color: #f7f7f7;
       }
       </style>
@endpush
@section('breadcrumb')
    @include('driver.components.breadcrumb', [
        'breadcrumbs' => [
            [
                'name' => __('Dashboard'),
                'url' => setRoute('driver.dashboard'),
            ],
        ],
        'active' => __('2FA Security'),
    ])
@endsection
@section('content')
    <div class="row mb-20-none">
        <div class="col-xl-6 col-lg-6 mb-20">
            <div class="two-authentic mt-10">
                <div class="dashboard-header-wrapper">
                  <h5 class="title">{{ __("Two Factor Authenticator") }}</h5>
                </div>
                <div class="card-body">
                    <form class="card-form">
                        <div class="row">
                            <div class="col-xl-12 col-lg-12 form-group">
                                <label>{{__("Two Factor Secret")}}<span>*</span></label>
                                <div class="input-group">
                                    <input type="text" class="form--control" id="referralURL"
                                        value="{{ auth('driver_gurd')->user()->two_factor_secret }}" readonly>
                                    <div class="input-group-text copytext"><i class="las la-copy"></i></div>
                                </div>
                            </div>
                            <div class="col-xl-12 col-lg-12 form-group">
                                <div class="qr-code-thumb text-center">
                                    <img class="mx-auto" style="width: 300px; height: 300px;" src="{{ $qr_code }}">
                                </div>
                            </div>
                        </div>
                        <div class="col-xl-12 col-md-12 mt-3">
                            @if (auth('driver_gurd')->user()->two_factor_status)
                                {{-- Disable Button --}}
                                <button type="button" class="btn--base bg--warning w-100 disable-2fa-btn">
                                    {{ __('Disable') }}
                                </button>
                                <div class="text--danger mt-3">
                                    {{ __("Don't forget to add this application in your google authentication app. Otherwise you can't login in your account.") }}
                                </div>
                            @else
                                {{-- Enable Button (open modal) --}}
                                <button type="button" class="btn--base w-100" data-bs-toggle="modal"
                                    data-bs-target="#otpModal">
                                    {{ __('Enable') }}
                                </button>
                            @endif
                        </div>
                    </form>
                </div>
            </div>
        </div>
        {{-- Right Side --}}
        <div class="col-xl-6 col-lg-6 mb-20">
            <div class="two-authentic mt-10">
                <div class="dashboard-header-wrapper">
                    <h4 class="title">{{ __("Google Authenticator") }}</h4>
                </div>
                <div class="card-body">
                <h6 class="mb-3">{{ __("Download Google Authenticator App") }}</h6>
                {{ __("Google Authenticator adds an extra layer of security to your online accounts by adding a second step of verification when you sign in. This means that in addition to your password, you'll also need to enter a code that is generated by the Google Authenticator app on your phone.") }}
                <a target="_blank" href="https://support.google.com/accounts/answer/1066447?hl=en&co=GENIE.Platform=Android" class="text--base">{{ __("How to Setup?") }}</a>
                <div class="play-store-thumb text-center mb-20 mt-3">
                    <img class="mx-auto" src="{{ asset('public/frontend') }}/images/element/authenticator.webp">
                </div>
                <a href="https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2" target="__blank" class="btn--base mt-10 w-100">
                   <i class="fab fa-google-play ms-1"> </i> {{ __("Download For Android") }}
                </a>
                  <a href="https://apps.apple.com/us/app/google-authenticator/id388497605" target="__blank" class="btn--base mt-10 w-100">
                   <i class="fab fa-apple ms-1"></i> {{ __("Download For IOS") }}
                </a>
            </div>
            </div>
        </div>
    </div>
    {{-- OTP Modal (for enabling 2FA) --}}
    <div class="modal fade" id="otpModal" tabindex="-1" aria-labelledby="otpModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header" id="otpModalLabel">
                    <h5 class="modal-title">{{__("Verify")}}</h5>
                    <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"
                        aria-label="Close"></button>
                </div>
                <form id="otpForm" method="POST" action="{{ setRoute('driver.security.google.2fa.verify') }}">
                    @csrf
                    <input type="hidden" name="target" value="1">
                    <div class="modal-body">
                        <div class="row mb-10-none">
                            <div class="col-xl-12 col-lg-12 form-group">
                                <label>{{__("Verify Code*")}}</label>
                                <input type="text" name="code" class="form--control"
                                    placeholder="Enter Google Authenticator Code..." required>
                            </div>
                        </div>
                    </div>
                    <div class="modal-2fa-footer">
                        <button type="submit" class="btn--base w-100">{{__("Verify")}}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection
@push('script')
    <script>
        // Disable Button → open confirm modal
        $(".disable-2fa-btn").click(function() {
            var actionRoute = "{{ setRoute('driver.security.google.2fa.status.update') }}";
            var target = 1;
            var btnText = $(this).text();
            var message =
                `{{ __('Are you sure to') }} <strong>${btnText}</strong> {{ __('2 factor authentication (Powered by google)?') }}`;
            openAlertModal(actionRoute, target, message, btnText, "POST");
        });
        // Copy text
        $('.copytext').on('click', function() {
            var copyText = document.getElementById("referralURL");
            copyText.select();
            copyText.setSelectionRange(0, 99999);
            document.execCommand("copy");
            throwMessage('success', ["Copied: " + copyText.value]);
        });
    </script>
@endpush