<?php

namespace Database\Seeders\Admin;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use  App\Models\Frontend\AnnouncementCategory;
use  App\Models\Frontend\Announcement;
 
class AnnouncementsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
       $category = AnnouncementCategory::firstOrCreate([
            'name' => '{"language":{"en":{"name":"Blog"},"es":{"name":null},"ar":{"name":null}}}',
            'status' => '1',
            'created_at' => now(),
            'updated_at' => now()
        ]);

    
        $announcements = array(
         array('announcement_category_id' => $category->id,'slug' => 'lorem-ipsum-d','data' => '{"language":{"en":{"title":"Lorem ipsum dolor sit amet consectetur","description":"<p><span style=\\"background-color:rgb(255,255,255);color:rgba(0,0,0,0.8);\\">Lorem ipsum dolor sit amet consectetur adipiscing elit habitasse interdum, purus sociis enim praesent potenti molestie erat luctus dui, in torquent non ridiculus hac nunc dictum vivamus. Lacus facilisi suspendisse eros rhoncus luctus posuere class natoque sollicitudin, congue magnis varius nam pellentesque tincidunt faucibus porttitor et, feugiat ornare imperdiet diam nunc vulputate euismod nostra. Sapien pulvinar integer non pellentesque mattis eu sociosqu, habitant aliquet senectus tortor odio dignissim purus, condimentum sagittis nisi primis urna potenti.<\\/span><\\/p>"},"es":{"title":null,"description":null},"ar":{"title":null,"description":null}},"image":"seeder/blog1.webp"}','status' => '1','created_at' => '2025-08-19 08:52:44','updated_at' => '2025-08-25 06:12:05'),
         array('announcement_category_id' => $category->id,'slug' => 'address-7ylb3pxafnmmcsf7-enable-google-authenticator','data' => '{"language":{"en":{"title":"Beyond Transactions: The Social Side of AdCrypto","description":"<p><span style=\\"background-color:rgb(255,255,255);color:rgb(34,34,34);\\">Google Authenticator adds an extra layer of security to your online accounts by adding a second step of verification when you sign in. This means that in addition to your password, you\'ll also need to enter a code that is generated by the Google Authenticator app on your phone. <\\/span><a href=\\"https:\\/\\/support.google.com\\/accounts\\/answer\\/1066447?hl=en&amp;co=GENIE.Platform=Android\\">How to Setup?<\\/a><\\/p>"},"es":{"title":null,"description":null},"ar":{"title":null,"description":null}},"image":"seeder/blog2.webp"}','status' => '1','created_at' => '2025-08-19 08:53:40','updated_at' => '2025-08-25 06:11:53'),
         array('announcement_category_id' => $category->id,'slug' => 'adcrypto-unleashed-exploring-advanced-features-for-power-users','data' => '{"language":{"en":{"title":"AdCrypto Unleashed: Exploring Advanced Features for Power Users","description":"<p><span style=\\"background-color:rgb(24,26,68);color:rgb(196,198,199);\\">Are you ready to take your crypto ventures to the next level? This blog unlocks the advanced features within AdCrypto tailored for power users. From real-time data analytics to navigating complex wallet management, explore the tools that empower seasoned crypto enthusiasts. Unleash the full potential of AdCrypto as we guide you through features designed to elevate your cryptocurrency experience. Join us on this journey and harness the power of AdCrypto for your advanced crypto endeavors.<\\/span><\\/p>"},"es":{"title":null,"description":null},"ar":{"title":null,"description":null}},"image":"seeder/blog3.webp"}','status' => '1','created_at' => '2025-08-19 08:55:36','updated_at' => '2025-08-25 06:09:43')
        );

      Announcement::insert($announcements);
    }
}
